dist: xenial
sudo: false

language: python
cache: pip

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov

script:
  - pytest --cov=ocxmd --cov-report=xml -v
after_success:
  codecov
